"""V0-S04 数据源与元数据中心

Revision ID: 398bf9ebf135
Revises:
Create Date: 2026-09-08 23:31:05.033085
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "398bf9ebf135"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """把控制库从上一版本升级到本版本。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datasource",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("POSTGRESQL", "MYSQL", "BIGQUERY", "SNOWFLAKE", name="datasource_kind"),
            nullable=False,
        ),
        sa.Column("host", sa.String(length=256), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("database_name", sa.String(length=128), nullable=False),
        sa.Column("credential_ref", sa.String(length=256), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "ERROR", name="datasource_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_datasource_slug"), "datasource", ["slug"], unique=True)
    op.create_table(
        "metadata_sync_job",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("datasource_id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "SUCCEEDED", "FAILED", name="sync_status"),
            nullable=False,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("tables_discovered", sa.Integer(), nullable=True),
        sa.Column("columns_discovered", sa.Integer(), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["datasource_id"], ["datasource.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metadata_sync_job_datasource_id"),
        "metadata_sync_job",
        ["datasource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_sync_job_idempotency_key"),
        "metadata_sync_job",
        ["idempotency_key"],
        unique=True,
    )
    op.create_table(
        "table_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("datasource_id", sa.Integer(), nullable=False),
        sa.Column("schema_name", sa.String(length=128), nullable=False),
        sa.Column("table_name", sa.String(length=128), nullable=False),
        sa.Column("table_type", sa.String(length=32), nullable=False),
        sa.Column("row_estimate", sa.Integer(), nullable=True),
        sa.Column("raw_comment", sa.Text(), nullable=True),
        sa.Column("manual_business_name", sa.String(length=256), nullable=True),
        sa.Column("manual_description", sa.Text(), nullable=True),
        sa.Column("manual_domain", sa.String(length=32), nullable=True),
        sa.Column("manual_grain", sa.Text(), nullable=True),
        sa.Column("manual_authoritative_source", sa.String(length=64), nullable=True),
        sa.Column("manual_aliases", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["datasource_id"], ["datasource.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("datasource_id", "schema_name", "table_name", name="uq_table_identity"),
    )
    op.create_index(
        op.f("ix_table_metadata_datasource_id"), "table_metadata", ["datasource_id"], unique=False
    )
    op.create_table(
        "column_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.Column("column_name", sa.String(length=128), nullable=False),
        sa.Column("ordinal_position", sa.Integer(), nullable=False),
        sa.Column("data_type", sa.String(length=64), nullable=False),
        sa.Column("character_maximum_length", sa.Integer(), nullable=True),
        sa.Column("numeric_precision", sa.Integer(), nullable=True),
        sa.Column("numeric_scale", sa.Integer(), nullable=True),
        sa.Column("is_nullable", sa.Boolean(), nullable=False),
        sa.Column("column_default", sa.Text(), nullable=True),
        sa.Column("is_primary_key", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("foreign_key_ref", sa.String(length=256), nullable=True),
        sa.Column("raw_comment", sa.Text(), nullable=True),
        sa.Column("manual_business_name", sa.String(length=256), nullable=True),
        sa.Column("manual_description", sa.Text(), nullable=True),
        sa.Column("manual_sensitivity", sa.String(length=32), nullable=True),
        sa.Column("manual_aliases", sa.Text(), nullable=True),
        sa.Column("sample_values", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["table_id"], ["table_metadata.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("table_id", "column_name", name="uq_column_identity"),
    )
    op.create_index(
        op.f("ix_column_metadata_table_id"), "column_metadata", ["table_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """仅在变更可安全回滚时实现降级；生成后需要人工审查。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_column_metadata_table_id"), table_name="column_metadata")
    op.drop_table("column_metadata")
    op.drop_index(op.f("ix_table_metadata_datasource_id"), table_name="table_metadata")
    op.drop_table("table_metadata")
    op.drop_index(op.f("ix_metadata_sync_job_idempotency_key"), table_name="metadata_sync_job")
    op.drop_index(op.f("ix_metadata_sync_job_datasource_id"), table_name="metadata_sync_job")
    op.drop_table("metadata_sync_job")
    op.drop_index(op.f("ix_datasource_slug"), table_name="datasource")
    op.drop_table("datasource")
    # 清理自定义枚举类型
    sa.Enum(name="sync_status").drop(op.get_bind())
    sa.Enum(name="datasource_status").drop(op.get_bind())
    sa.Enum(name="datasource_kind").drop(op.get_bind())
    # ### end Alembic commands ###
