"""V0-S05 索引状态控制面

Revision ID: 6bdae843a9d5
Revises: 398bf9ebf135
Create Date: 2026-09-08 23:40:48.531983
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6bdae843a9d5"
down_revision: str | Sequence[str] | None = "398bf9ebf135"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """把控制库从上一版本升级到本版本。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "index_batch",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("index_type", sa.String(length=64), nullable=False),
        sa.Column("batch_key", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "BUILDING", "PUBLISHED", "FAILED", name="index_batch_status"),
            nullable=False,
        ),
        sa.Column("object_count", sa.Integer(), nullable=True),
        sa.Column("embedding_model_version", sa.String(length=128), nullable=True),
        sa.Column("dimension", sa.Integer(), nullable=True),
        sa.Column("metadata_version", sa.String(length=64), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("index_type", "batch_key", name="uq_index_batch_key"),
    )
    op.create_table(
        "published_index_version",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("index_type", sa.String(length=64), nullable=False),
        sa.Column("index_batch_id", sa.Integer(), nullable=False),
        sa.Column("embedding_model_version", sa.String(length=128), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("object_count", sa.Integer(), nullable=False),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("index_type", name="uq_published_index_type"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """仅在变更可安全回滚时实现降级；生成后需要人工审查。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("published_index_version")
    op.drop_table("index_batch")
    # ### end Alembic commands ###
